### PR TITLE
Adds exception handling for failed builds and missing assemblies

### PR DESCRIPTION
**Pull request by mbartelsm**
Adds exception handling for a couple of methods and addresses the inability to read .exe files.

### CODE REVIEW

**Comment by mbartelsm** [comment]
Ignore the huge amount of commits, that's only because I had to rebase to main

**Comment by mbartelsm** [comment]
**Squash and merge** instead of a plain merge would be better, I don't know why git made so many duplicate commits.

**Comment by mbartelsm** [comment]
@cdadashovkhandan why 918239b here?

**Comment by cdadashovkhandan** [comment]
Probably because I was trying to fix the bug on this branch too, for some reason. That commit should be undone regardless, sorry about that.

**Pull request merged**
